/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mediatheque.Jframes;

import java.awt.Color;

/**
 *
 * @author asus
 */
public class Parameters extends javax.swing.JFrame {

    /**
     * Creates new form Parameters
     */
    public Parameters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tfUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tfPassword1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblDictionaries = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblParameters = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblHome = new javax.swing.JLabel();
        lblFavorites = new javax.swing.JLabel();
        lblKindles = new javax.swing.JLabel();
        lblBooks = new javax.swing.JLabel();
        lblMagazines = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(22, 26, 48));
        jPanel1.setForeground(new java.awt.Color(22, 26, 48));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(49, 48, 77));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setAlignmentX(50.0F);
        jPanel3.setAlignmentY(50.0F);
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfUsername.setBackground(new java.awt.Color(217, 217, 217));
        tfUsername.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(22, 26, 48));
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        jPanel3.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 320, 40));

        jLabel2.setBackground(new java.awt.Color(191, 191, 191));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(191, 191, 191));
        jLabel2.setText("Change Username");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        tfPassword.setBackground(new java.awt.Color(217, 217, 217));
        tfPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(22, 26, 48));
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 320, 40));

        jLabel3.setBackground(new java.awt.Color(191, 191, 191));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(191, 191, 191));
        jLabel3.setText("Change Password");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jButton2.setBackground(new java.awt.Color(217, 217, 217));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(22, 26, 48));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 150, 40));

        tfPassword1.setBackground(new java.awt.Color(217, 217, 217));
        tfPassword1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfPassword1.setForeground(new java.awt.Color(22, 26, 48));
        tfPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassword1ActionPerformed(evt);
            }
        });
        jPanel3.add(tfPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 320, 40));

        jLabel5.setBackground(new java.awt.Color(191, 191, 191));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(191, 191, 191));
        jLabel5.setText("Change CNE");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 407, 360));

        jLabel1.setBackground(new java.awt.Color(191, 191, 191));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(191, 191, 191));
        jLabel1.setText("Modify your infos!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 78));

        jPanel4.setBackground(new java.awt.Color(49, 48, 77));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel4.setAlignmentX(50.0F);
        jPanel4.setAlignmentY(50.0F);
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDictionaries.setBackground(new java.awt.Color(22, 26, 48));
        lblDictionaries.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblDictionaries.setForeground(new java.awt.Color(217, 217, 217));
        lblDictionaries.setText("  Dictionaries");
        lblDictionaries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDictionariesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDictionariesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDictionariesMouseExited(evt);
            }
        });
        jPanel4.add(lblDictionaries, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 160, 30));

        lblLogout.setBackground(new java.awt.Color(22, 26, 48));
        lblLogout.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(217, 217, 217));
        lblLogout.setText("  Log Out");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });
        jPanel4.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 160, 30));

        lblParameters.setBackground(new java.awt.Color(22, 26, 48));
        lblParameters.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblParameters.setForeground(new java.awt.Color(217, 217, 217));
        lblParameters.setText("  Parameters");
        lblParameters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblParametersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblParametersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblParametersMouseExited(evt);
            }
        });
        jPanel4.add(lblParameters, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 160, 30));

        jSeparator1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 160, 10));

        lblHome.setBackground(new java.awt.Color(22, 26, 48));
        lblHome.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblHome.setForeground(new java.awt.Color(217, 217, 217));
        lblHome.setText("  Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });
        jPanel4.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 30));

        lblFavorites.setBackground(new java.awt.Color(22, 26, 48));
        lblFavorites.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblFavorites.setForeground(new java.awt.Color(217, 217, 217));
        lblFavorites.setText("  My Favorites");
        lblFavorites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFavoritesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFavoritesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFavoritesMouseExited(evt);
            }
        });
        jPanel4.add(lblFavorites, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 30));

        lblKindles.setBackground(new java.awt.Color(22, 26, 48));
        lblKindles.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblKindles.setForeground(new java.awt.Color(217, 217, 217));
        lblKindles.setText("  My Kindles");
        lblKindles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKindlesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKindlesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKindlesMouseExited(evt);
            }
        });
        jPanel4.add(lblKindles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 30));

        lblBooks.setBackground(new java.awt.Color(22, 26, 48));
        lblBooks.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblBooks.setForeground(new java.awt.Color(217, 217, 217));
        lblBooks.setText("  Books");
        lblBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBooksMouseExited(evt);
            }
        });
        jPanel4.add(lblBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 30));

        lblMagazines.setBackground(new java.awt.Color(22, 26, 48));
        lblMagazines.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblMagazines.setForeground(new java.awt.Color(217, 217, 217));
        lblMagazines.setText("  Magazines");
        lblMagazines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMagazinesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMagazinesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMagazinesMouseExited(evt);
            }
        });
        jPanel4.add(lblMagazines, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, 30));

        jPanel2.setBackground(new java.awt.Color(22, 26, 48));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 160, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassword1ActionPerformed

    private void lblDictionariesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDictionariesMouseClicked
        Dictionaries dictionaries =new Dictionaries();
        dictionaries.setVisible(true);
        dictionaries.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblDictionariesMouseClicked

    private void lblDictionariesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDictionariesMouseEntered
        lblDictionaries.setBackground(new Color(80,78,128));
        lblDictionaries.setOpaque(true);
    }//GEN-LAST:event_lblDictionariesMouseEntered

    private void lblDictionariesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDictionariesMouseExited
        lblDictionaries.setOpaque(false);
        lblDictionaries.setBackground(null);
    }//GEN-LAST:event_lblDictionariesMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        Login login =new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setBackground(new Color(80,78,128));
        lblLogout.setOpaque(true);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setBackground(null);
        lblLogout.setOpaque(false);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblParametersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblParametersMouseClicked
        
    }//GEN-LAST:event_lblParametersMouseClicked

    private void lblParametersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblParametersMouseEntered
       
    }//GEN-LAST:event_lblParametersMouseEntered

    private void lblParametersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblParametersMouseExited
        
    }//GEN-LAST:event_lblParametersMouseExited

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        Home home =new Home();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setBackground(new Color(80,78,128));
        lblHome.setOpaque(true);
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setBackground(null);
        lblHome.setOpaque(false);
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblFavoritesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFavoritesMouseClicked
        Favorites favorites =new Favorites();
        favorites.setVisible(true);
        favorites.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblFavoritesMouseClicked

    private void lblFavoritesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFavoritesMouseEntered
        lblFavorites.setBackground(new Color(80,78,128));
        lblFavorites.setOpaque(true);
    }//GEN-LAST:event_lblFavoritesMouseEntered

    private void lblFavoritesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFavoritesMouseExited
        lblFavorites.setOpaque(false);
        lblFavorites.setBackground(null);
    }//GEN-LAST:event_lblFavoritesMouseExited

    private void lblKindlesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKindlesMouseClicked
        Kindles kindles =new Kindles();
        kindles.setVisible(true);
        kindles.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblKindlesMouseClicked

    private void lblKindlesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKindlesMouseEntered
        lblKindles.setBackground(new Color(80,78,128));
        lblKindles.setOpaque(true);
    }//GEN-LAST:event_lblKindlesMouseEntered

    private void lblKindlesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKindlesMouseExited
        lblKindles.setOpaque(false);
        lblKindles.setBackground(null);
    }//GEN-LAST:event_lblKindlesMouseExited

    private void lblBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBooksMouseClicked
        Books books =new Books();
        books.setVisible(true);
        books.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblBooksMouseClicked

    private void lblBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBooksMouseEntered
        lblBooks.setBackground(new Color(80,78,128));
        lblBooks.setOpaque(true);
    }//GEN-LAST:event_lblBooksMouseEntered

    private void lblBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBooksMouseExited
        lblBooks.setOpaque(false);
        lblBooks.setBackground(null);
    }//GEN-LAST:event_lblBooksMouseExited

    private void lblMagazinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMagazinesMouseClicked
        Magazines magazines =new Magazines();
        magazines.setVisible(true);
        magazines.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblMagazinesMouseClicked

    private void lblMagazinesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMagazinesMouseEntered
        lblMagazines.setBackground(new Color(80,78,128));
        lblMagazines.setOpaque(true);
    }//GEN-LAST:event_lblMagazinesMouseEntered

    private void lblMagazinesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMagazinesMouseExited
        lblMagazines.setOpaque(false);
        lblMagazines.setBackground(null);
    }//GEN-LAST:event_lblMagazinesMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parameters().setVisible(true);
                Parameters parameters = new Parameters();
                parameters.setVisible(true);
                parameters.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBooks;
    private javax.swing.JLabel lblDictionaries;
    private javax.swing.JLabel lblFavorites;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblKindles;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblMagazines;
    private javax.swing.JLabel lblParameters;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfPassword1;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
